' Preview durch <Alt>D

@startuml Aktivitätsdiagramm_BuchAnlegen

title Aktivitätsdiagramm – Buch neu anlegen (Admin)

start

:Eingabeformular für Buchdaten anzeigen;
:Eingabe Daten;

:Button "Anlegen" klicken;
:Validierung der Eingaben;

if ("Daten korrekt?") then ([ja])
  :POST-Request an Backend senden;
  if ("Buch erfolgreich angelegt?") then ([ja])
    :Popup: Buch wurde erfolgreich angelegt;
  else ([nein])
    :Popup: Fehler beim Anlegen (z.B. doppelte ISBN);
  endif
else ([nein])
  :Popup: Eingabefehler erkannt;
endif

:Rückkehr zum Eingabeformular;

stop

@enduml