' Preview durch <Alt>D

@startuml Aktivitätsdiagramm_Bewertung

title Aktivitätsdiagramm – Buch bewerten (Admin)

start

:Suchergebnisse anzeigen;
:Aktuelle Bewertung anzeigen (1-5 Sterne);

:Neue Bewertung abgeben;
:Neue Bewertung wird gesendet;

if ("Bewertung erfolgreich gespeichert?") then ([ja])
  :Sterne werden sofort aktualisiert (ohne Reload);
else ([nein])
  :Fehlermeldung anzeigen;
endif

stop

@enduml